export enum ConfigFlag {
    DISABLE_AUTO_WEAPON_SWAP = 'DISABLE_AUTO_WEAPON_SWAP',
    DISABLE_PED_PROP_KNOCK_OFF = 'DISABLE_PED_PROP_KNOCK_OFF',
    DISABLE_IDLE_CAMERA = 'DISABLE_IDLE_CAMERA',
    DISABLE_VEHICLE_ENGINE_SHUTDOWN_ON_LEAVE = 'DISABLE_VEHICLE_ENGINE_SHUTDOWN_ON_LEAVE',
    DISABLE_SP_ENTER_VEHICLE_CLIPSET = 'DISABLE_SP_ENTER_VEHICLE_CLIPSET',
    FORCE_RENDER_SNOW = 'FORCE_RENDER_SNOW',
    FORCE_HIDE_NIGHT_PROPS = 'FORCE_HIDE_NIGHT_PROPS',
    FORCE_SHOW_NIGHT_PROPS = 'FORCE_SHOW_NIGHT_PROPS',
    DISABLE_EMISSIVE_LIGHTS_RENDERING = 'DISABLE_EMISSIVE_LIGHTS_RENDERING',
}
