export enum WeatherType {
    EXTRA_SUNNY = 0,
    CLEAR = 1,
    CLOUDS = 2,
    SMOG = 3,
    FOGGY = 4,
    OVERCAST = 5,
    RAIN = 6,
    THUNDER = 7,
    LIGHT_RAIN = 8,
    SMOGGY_LIGHT_RAIN = 9,
    VERY_LIGHT_SNOW = 10,
    WINDY_LIGHT_SNOW = 11,
    LIGHT_SNOW = 12,
    CHRISTMAS = 13,
    HALLOWEEN = 14,
}
