export const THROTTLER_LIMIT = 'THROTTLER_LIMIT';
export const THROTTLER_TTL = 'THROTTLER_TTL';
export const THROTTLER_OPTIONS = 'THROTTLER_MODULE_OPTIONS';
export const THROTTLER_SKIP = 'THROTTLER_SKIP';
export const THROTTLER_STORAGE = 'THROTTLER_STORAGE';
