export const INTERNAL_APP_CONTAINER = 'INTERNAL_APP_CONTAINER';
export const GLOBAL_APP_CONTAINER = 'GLOBAL_APP_CONTAINER';
export const APP_ENVIROMENT = 'APP_ENVIROMENT';

export const GLOBAL_GUARDS = 'GLOBAL_GUARDS';
export const GLOBAL_INTERCEPTORS = 'GLOBAL_INTERCEPTORS';
export const GLOBAL_PIPES = 'GLOBAL_PIPES';
export const GLOBAL_ERROR_FILTERS = 'GLOBAL_ERROR_FILTERS';

export const INTERNAL_PLUGINS = 'INTERNAL_PLUGINS';
export const EXTERNAL_PLUGINS = 'EXTERNAL_PLUGINS';

export const ENABLE_SHUTDOWN_HOOKS = 'ENABLE_SHUTDOWN_HOOKS';
export const LOG_ERROR_STACKTRACE = 'LOG_ERROR_STACKTRACE';

export const MANGO_LOG_PREFIX = '🥭Mango';

export const MANGO_REQUEST_FACTORY = 'MANGO_REQUEST_FACTORY';
export const MANGO_RESPONSE_FACTORY = 'MANGO_RESPONSE_FACTORY';
export const EXECUTION_CONTEXT_FACTORY = 'EXECUTION_CONTEXT_FACTORY';
